### ISSUE TITLE
extra whitespace in name in prompts

### ISSUE THREAD

**Issue by jdv** [antononcube/Raku-LLM-Prompts#1]
https://github.com/antononcube/Raku-LLM-Prompts/blob/main/resources/prompts.json#L8208

**Comment by antononcube** [comment]
Thank you, good catch!

Fixed in the few places I found those extra spaces. See: [28a9932](https://github.com/antononcube/Raku-LLM-Prompts/commit/28a99327c9a3d087a783d63d94903a3ca6509493).
